# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b9afa6f6221bb7a78c08002cd428152082f132705fecb0b78212f26f30e211ff8d8ff2937f171c458230ec77f1929a174a9e0f9d7b5a57cd4135534a69624c

test:
  secret_key_base: 438ab9b49bd13a644dedbe8015d638ec8324491341527c8cf1893057990eb58ca8827876a4bc6fbce0b30be61c7c5e62e71451c89d73ad4fac9242089173d803

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
